"""empty message

Revision ID: 2144fd0d50c4
Revises: 8614c800510e
Create Date: 2021-01-10 13:23:58.892581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2144fd0d50c4'
down_revision = '8614c800510e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('question', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_answers', 'question', ['question'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_column('user_answers', 'question')
    # ### end Alembic commands ###
