"""empty message

Revision ID: 24f7ddd5d5c2
Revises: 2144fd0d50c4
Create Date: 2021-01-10 17:13:33.314705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f7ddd5d5c2'
down_revision = '2144fd0d50c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u_res', sa.Integer(), nullable=True),
    sa.Column('t_res', sa.Integer(), nullable=True),
    sa.Column('result', sa.Float(precision=10), nullable=True),
    sa.Column('max', sa.Float(precision=10), nullable=True),
    sa.Column('right', sa.Float(precision=10), nullable=True),
    sa.Column('error', sa.Float(precision=10), nullable=True),
    sa.ForeignKeyConstraint(['t_res'], ['test.id'], ),
    sa.ForeignKeyConstraint(['u_res'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'user_answers', 'question', ['question'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_table('user_results')
    # ### end Alembic commands ###
