"""empty message

Revision ID: 8614c800510e
Revises: 5194a8c7a0da
Create Date: 2021-01-10 13:19:29.562461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8614c800510e'
down_revision = '5194a8c7a0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('answers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answers'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    # ### end Alembic commands ###
